# frozen_string_literal: true

require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.test_files = Dir[__dir__ + '/test/**/test_*.rb']
  t.libs << 'test'
  t.verbose = false
end

task :gem do
  sh('gem build *.gemspec')
end

task default: :test
