name: adsf

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.0", "3.1", "3.2", "3.3"]

    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: bundler-b-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('Gemfile') }}

      - run: |
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs "$(nproc)"

      - name: Test style
        if: ${{ matrix.ruby-version == '3.1' }}
        run: bundle exec rake rubocop

      - name: Test adsf
        run: bundle exec rake adsf:test
        timeout-minutes: 3

      - name: Test adsf-live
        run: bundle exec rake adsf_live:test
        timeout-minutes: 3
